### ISSUE TITLE
I don't see Kong available under marketplace with Kubernetes support

### ISSUE THREAD

**Issue by rohgoyal** [Kong/google-marketplace-kong-app#2]
Hi, I am looking for help with following
1. I tried Kong available under Marketplace on Google Compute Engine. Understand this image is created by bitnami which internally run Community Edition. Do you know when Kong will be available on Kubernetes Engine via the Marketplace? 
2. I don't see any great documentation explaining how to run Kong Enterprise Edition in Google Cloud. Can you point to any?
Cheers-

**Comment by coopr** [comment]
Hi @rohgoyal - we hope to have Kong available on Kubernetes via the Google Marketplace in the coming weeks. We don't yet have documentation specific to Kong Enterprise Edition on Google Cloud, but hopefully our existing docs at https://docs.konghq.com/enterprise/ and https://konghq.com/install/ will suffice. Note that we welcome pull requests to improve our documentation https://github.com/Kong/docs.konghq.com
